# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cover.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap


class Coverpage(object):
    def __init__(self, window):
        self.window = window

    def mainpage(self):
        self.window.hide()
        from mainpage import Ui_Dialog
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Dialog()
        self.ui.setupUi(self.window)
        self.window.show()
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(596, 450)
        Dialog.setStyleSheet("")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(-10, -10, 611, 461))
        self.label.setPixmap(QPixmap('1c3b4f4622241.560c2eb1af601.jpg'))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(30, 110, 101, 41))
        self.label_5.setStyleSheet("font-family: times new roman;\n"
"font-size: 13px;\n"
"color: black;\n"
"font-style: italic;")
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 50, 161, 41))
        self.label_2.setStyleSheet("font-family: times new roman;\n"
"font-size: 30px;\n"
"color: black;\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 90, 91, 31))
        self.label_3.setStyleSheet("font-family: times new roman;\n"
"font-size: 13px;\n"
"color: black;\n"
"font-style: italic;\n"
"")
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(20, 360, 101, 41))
        self.pushButton.setStyleSheet("QPushButton\n"
"{\n"
"Background:#F3F6FF;\n"
"color: black;\n"
"font-family: times new roman;\n"
"font-size: 15px;\n"
"font-style: bold;\n"
"border-radius: 15px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background: #0068FF;\n"
"color: white;\n"
"border: 1px solid white;\n"
"\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.mainpage)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dictionary"))
        self.label_5.setText(_translate("Dialog", "/\'dik.sh.ē.n.ē.ri/"))
        self.label_2.setText(_translate("Dialog", "Dictionary"))
        self.label_3.setText(_translate("Dialog", "noun [ C ]"))
        self.pushButton.setText(_translate("Dialog", "Get Started"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Coverpage(Dialog)
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
